version:  '3.3'
services:
  dbMysql:
    image: mysql:8.0
    command:  --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD:  L1l1@n3
      MYSQL_DATABASE:  titas
      MYSQL_USER:  acf
      MYSQL_PASSWORD:  password
    ports:
      - 5555:3306

  adminer: 
    image: adminer
    ports:
      - 8080:8080

  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    ports:
      - 8182:80

